//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Cfx.Spa.Routing {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Cfx.Spa.Routing.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complete Neutronium Vue Demo.
        /// </summary>
        internal static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Including Ioc, navigation (vue-router) internalization (vue-i18n) and chromeless window.
        /// </summary>
        internal static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Made with vuetify framework.
        /// </summary>
        internal static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmation needed.
        /// </summary>
        internal static string ConfirmationNeeded {
            get {
                return ResourceManager.GetString("ConfirmationNeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to close application?.
        /// </summary>
        internal static string DoYouWantToCloseApplication {
            get {
                return ResourceManager.GetString("DoYouWantToCloseApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart application?.
        /// </summary>
        internal static string DoYouWantToRestartApplication {
            get {
                return ResourceManager.GetString("DoYouWantToRestartApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go To About Section.
        /// </summary>
        internal static string GoToAboutSection {
            get {
                return ResourceManager.GetString("GoToAboutSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to made by.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_about {
            get {
                return ResourceManager.GetString("Menu_about", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Menu_main {
            get {
                return ResourceManager.GetString("Menu_main", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neutronium Vue SPA Template including IoC, routing and internalization.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        internal static string ToDo {
            get {
                return ResourceManager.GetString("ToDo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ToDo List.
        /// </summary>
        internal static string ToDoList {
            get {
                return ResourceManager.GetString("ToDoList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What needs to be done?.
        /// </summary>
        internal static string WhatNeedsToBeDone {
            get {
                return ResourceManager.GetString("WhatNeedsToBeDone", resourceCulture);
            }
        }
    }
}
